package moe.flinty.yomark.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// 由 tools/theme/gen_theme_palettes.mjs 生成，不要手改。
// 算法是 Material Color Utilities 的 SchemeContent（主色贴近种子色），每套注明了种子色。

internal object ThemePalettes {

    /** 种子色 #1A73E8 */
    val blue: ColorScheme = lightColorScheme(
        primary = Color(0xFF005BBF),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF1A73E8),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFADC7FF),
        secondary = Color(0xFF475E8C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFB2C9FE),
        onSecondaryContainer = Color(0xFF3D5481),
        tertiary = Color(0xFF8C36AB),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFA851C6),
        onTertiaryContainer = Color(0xFFFFFFFF),
        background = Color(0xFFF9F9FF),
        onBackground = Color(0xFF191C23),
        surface = Color(0xFFF9F9FF),
        onSurface = Color(0xFF191C23),
        surfaceVariant = Color(0xFFDEE2F2),
        onSurfaceVariant = Color(0xFF414754),
        surfaceTint = Color(0xFF005BC0),
        inverseSurface = Color(0xFF2D3038),
        inverseOnSurface = Color(0xFFEFF0FA),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF727785),
        outlineVariant = Color(0xFFC1C6D6),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF9F9FF),
        surfaceContainer = Color(0xFFECEDF7),
        surfaceContainerHigh = Color(0xFFE6E8F2),
        surfaceContainerHighest = Color(0xFFE0E2EC),
        surfaceContainerLow = Color(0xFFF2F3FD),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD8D9E3),
    )

    /** 种子色 #00897B */
    val teal: ColorScheme = lightColorScheme(
        primary = Color(0xFF00685D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF008376),
        onPrimaryContainer = Color(0xFFF4FFFB),
        inversePrimary = Color(0xFF70D8C8),
        secondary = Color(0xFF41655F),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFC3EBE2),
        onSecondaryContainer = Color(0xFF476B65),
        tertiary = Color(0xFF684F94),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF8168AE),
        onTertiaryContainer = Color(0xFFFFFBFF),
        background = Color(0xFFF6FAF8),
        onBackground = Color(0xFF171D1B),
        surface = Color(0xFFF6FAF8),
        onSurface = Color(0xFF171D1B),
        surfaceVariant = Color(0xFFD8E5E1),
        onSurfaceVariant = Color(0xFF3D4946),
        surfaceTint = Color(0xFF006B5F),
        inverseSurface = Color(0xFF2C3130),
        inverseOnSurface = Color(0xFFEDF2EF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF6D7A77),
        outlineVariant = Color(0xFFBCC9C5),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF6FAF8),
        surfaceContainer = Color(0xFFEAEFEC),
        surfaceContainerHigh = Color(0xFFE4E9E7),
        surfaceContainerHighest = Color(0xFFDFE4E1),
        surfaceContainerLow = Color(0xFFF0F5F2),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD6DBD9),
    )

    /** 种子色 #43A047 */
    val green: ColorScheme = lightColorScheme(
        primary = Color(0xFF006B1B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF268630),
        onPrimaryContainer = Color(0xFFF7FFF1),
        inversePrimary = Color(0xFF7DDC7A),
        secondary = Color(0xFF446741),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFC2EABA),
        onSecondaryContainer = Color(0xFF486B45),
        tertiary = Color(0xFF006192),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF007BB7),
        onTertiaryContainer = Color(0xFFFCFCFF),
        background = Color(0xFFF6FBF0),
        onBackground = Color(0xFF181D16),
        surface = Color(0xFFF6FBF0),
        onSurface = Color(0xFF181D16),
        surfaceVariant = Color(0xFFDBE6D4),
        onSurfaceVariant = Color(0xFF3F4A3D),
        surfaceTint = Color(0xFF006E1C),
        inverseSurface = Color(0xFF2C322A),
        inverseOnSurface = Color(0xFFEDF3E7),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF6F7A6B),
        outlineVariant = Color(0xFFBFCAB9),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF6FBF0),
        surfaceContainer = Color(0xFFEAF0E4),
        surfaceContainerHigh = Color(0xFFE5EADF),
        surfaceContainerHighest = Color(0xFFDFE4D9),
        surfaceContainerLow = Color(0xFFF0F5EA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFD6DCD1),
    )

    /** 种子色 #F57C00 */
    val orange: ColorScheme = lightColorScheme(
        primary = Color(0xFF964900),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFF57C00),
        onPrimaryContainer = Color(0xFF572800),
        inversePrimary = Color(0xFFFFB786),
        secondary = Color(0xFF895026),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFEB380),
        onSecondaryContainer = Color(0xFF794319),
        tertiary = Color(0xFF5F6200),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF9FA400),
        onTertiaryContainer = Color(0xFF353700),
        background = Color(0xFFFFF8F5),
        onBackground = Color(0xFF241912),
        surface = Color(0xFFFFF8F5),
        onSurface = Color(0xFF241912),
        surfaceVariant = Color(0xFFFCDCCA),
        onSurfaceVariant = Color(0xFF574235),
        surfaceTint = Color(0xFF964900),
        inverseSurface = Color(0xFF3B2E26),
        inverseOnSurface = Color(0xFFFFEDE4),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF8B7263),
        outlineVariant = Color(0xFFDEC1AF),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F5),
        surfaceContainer = Color(0xFFFFEADE),
        surfaceContainerHigh = Color(0xFFFAE4D8),
        surfaceContainerHighest = Color(0xFFF4DED2),
        surfaceContainerLow = Color(0xFFFFF1EA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFEBD6CA),
    )

    /** 种子色 #E53935 */
    val red: ColorScheme = lightColorScheme(
        primary = Color(0xFFB7131A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDB322F),
        onPrimaryContainer = Color(0xFFFFFBFF),
        inversePrimary = Color(0xFFFFB4AC),
        secondary = Color(0xFFA13D36),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFF857A),
        onSecondaryContainer = Color(0xFF751D19),
        tertiary = Color(0xFF845000),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFA66600),
        onTertiaryContainer = Color(0xFFFFFBFF),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF271716),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF271716),
        surfaceVariant = Color(0xFFFFDAD6),
        onSurfaceVariant = Color(0xFF5B403D),
        surfaceTint = Color(0xFFBB171C),
        inverseSurface = Color(0xFF3E2C2A),
        inverseOnSurface = Color(0xFFFFEDEA),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF906F6C),
        outlineVariant = Color(0xFFE4BEB9),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainer = Color(0xFFFFE9E6),
        surfaceContainerHigh = Color(0xFFFFE2DE),
        surfaceContainerHighest = Color(0xFFFADCD8),
        surfaceContainerLow = Color(0xFFFFF0EE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFF1D3D0),
    )

    /** 种子色 #D81B60 */
    val pink: ColorScheme = lightColorScheme(
        primary = Color(0xFFB0004A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD81B60),
        onPrimaryContainer = Color(0xFFFFF2F3),
        inversePrimary = Color(0xFFFFB2BF),
        secondary = Color(0xFFA33855),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFC7E9A),
        onSecondaryContainer = Color(0xFF741333),
        tertiary = Color(0xFF9D3500),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFC64500),
        onTertiaryContainer = Color(0xFFFFF3F0),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF27171A),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF27171A),
        surfaceVariant = Color(0xFFFFD9DE),
        onSurfaceVariant = Color(0xFF5A4044),
        surfaceTint = Color(0xFFBC004F),
        inverseSurface = Color(0xFF3E2C2F),
        inverseOnSurface = Color(0xFFFFECEE),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        outline = Color(0xFF8E6F74),
        outlineVariant = Color(0xFFE3BDC3),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainer = Color(0xFFFFE9EB),
        surfaceContainerHigh = Color(0xFFFFE1E5),
        surfaceContainerHighest = Color(0xFFF9DBDF),
        surfaceContainerLow = Color(0xFFFFF0F1),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFF0D3D7),
    )
}
